### ISSUE TITLE
Add ability to evict an AFK dealer

### ISSUE THREAD

**Issue by dev-null-matt** [dev-null-matt/devops-against-humanity#2]
Command: `hubot devops evict dealer`
- [ ] If more than half the current players (min 2) issue this command, the current round immediately ends and a new dealer is selected from among the people that issued the command.
- [ ] The dealer can not vote to evict themselves.

**Comment by thekbb** [comment]
I've been waiting on this for years, @dev-null-matt

**Comment by thekbb** [comment]
Still waiting, @dev-null-matt

**Comment by thekbb** [comment]
@dev-null-matt I'm loosing hope....

**Comment by thekbb** [comment]
It's been another year, @dev-null-matt ....

**Comment by dev-null-matt** [comment]
Bro, you're almost certainly a better programmer than me. Maybe you can do it.

**Comment by thekbb** [comment]
I have been checking this for progress every day. That's 2,255 days. I can't take the daily disappointment anymore. closing.
